### ISSUE TITLE
Deregistering a service does not work in Docker Compose

### ISSUE THREAD

**Issue by remmelt** [jippi/hashi-ui#271]
Use this `docker-compose.yml`:

```
version: '3'
services:
  consul:
    image: consul
  registrator:
    image: gliderlabs/registrator
    command: -ip=127.0.0.1 consul://consul:8500
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
  hashi-ui:
    image: jippi/hashi-ui
    ports:
    - "8000:3000"
    environment:
      CONSUL_ENABLE: 1
      CONSUL_ADDR: consul:8500
```

As expected, a service called `consul` appears in http://localhost:8000/consul/dc1/services/consul and a `hashi-ui` service is at http://localhost:8000/consul/dc1/services/hashi-ui

Clicking the DEREGISTER button should call the Consul service running as host `consul` due to Docker Compose's registration of host names. This is where it gets its initial information as well.
Instead, it tries to connect to a Consul agent running on `localhost`, but there is none because hashi-ui is running in a container.

Is there a way to have the deregistration call the `CONSUL_ADDR` instead of `localhost`?

**Comment by remmelt** [comment]
This only works when you set the bind interface:
```
services:
  consul:
    image: consul
    environment:
      CONSUL_BIND_INTERFACE: eth0
```

So: not a bug. 🎉
